#!/usr/bin/env php
<?php
foreach ([
    __DIR__. '/vendor/squizlabs/php_codesniffer/autoload.php',
    __DIR__.'/../../autoload.php',
    __DIR__.'/../vendor/autoload.php',
    __DIR__.'/vendor/autoload.php'
    ] as $file) {

    if (file_exists($file)) {
        require $file;
        break;
    }
}

unset($file);

if (class_exists(\PHP_CodeSniffer_CLI::class)) {
    (new \SugaredRim\PHP\CodeSniffer\CLI())->runphpcs();
} else {
    exit((new \SugaredRim\PHP\CodeSniffer\Runner())->runPHPCS());
}
